### ISSUE TITLE
你好 请问最后去水印效果怎么样，我最近也在尝试用gan去水印

### ISSUE THREAD

**Issue by wgh-2018** [SleepSupreme/GAN-for-Digital-Watermarks#1]

**Comment by chenguolin** [comment]
这个是个正在进行的项目，所以文档啥的还不完善。我这个项目不是用来去（可见）水印的，是用来伪造数字水印的（不可见）。GANs或者CNN去可见水印的相关研究很多的，可以参考下：Towards Photo-Realistic Visible Watermark Removal with Conditional Generative Adversarial Networks；Large-Scale Visible Watermark Detection and Removal with Deep Convolutional Networks这两篇。
