### ISSUE TITLE
real_watermark cannot be extracted from real_B_img

### ISSUE THREAD

**Issue by 1685044068** [SleepSupreme/GAN-for-Digital-Watermarks#3]
I created the dataset through embed_dataset in wm_util.py, but real_watermark cannot be extracted from real_B_img during training, Here's my train_opt.txt

[train_opt.txt](https://github.com/chenguolin/WatermarkFaker/files/13376158/train_opt.txt)
![result](https://github.com/chenguolin/WatermarkFaker/assets/50684558/eb11e41a-0864-4323-9cb4-1eac20f8d342)

**Comment by chenguolin** [comment]
Have you tried to extract the ground-truth watermark by `extract()` as [this line](https://github.com/chenguolin/WatermarkFaker/blob/05647082947f5a2de9f9e0da96eb36a9e1462922/watermarks/lsb.py#L45)?

My suggestion is to make sure you can extract the real watermark from the training dataset before starting training a neural network.

It seems that you failed to extract even the real watermark. Make sure `wm_alg.extract(wm_alg.embed(image, watermark))` is close to `watermark`, where `wm_alg` is an instance of class `BaseWatermark`.

**Comment by chenguolin** [comment]
Inside the model, real watermark is extracted by [this line](https://github.com/chenguolin/WatermarkFaker/blob/05647082947f5a2de9f9e0da96eb36a9e1462922/models/pix2pix_model.py#L99), and fake watermark is extracted by [this line](https://github.com/chenguolin/WatermarkFaker/blob/05647082947f5a2de9f9e0da96eb36a9e1462922/models/pix2pix_model.py#L123). You can check these inputs and outputs first before training the network.

**Comment by 1685044068** [comment]
Thank you for your help, I found the problem, It is valid if the result of alg.embed is taken directly as the result of alg.extract but when I save watermark_ and re-read it, I can't extract the watermarked image. Can you tell me the details of how you made the dataset？I used watermarks.lsb for embedding and utils.wm_util.py to create the dataset.
![result](https://github.com/chenguolin/WatermarkFaker/assets/50684558/4b2451ab-f9e5-434c-956b-71f8b1f562af)
![result2](https://github.com/chenguolin/WatermarkFaker/assets/50684558/41d369d9-b065-4379-8054-842bbfa8d54b)

**Comment by chenguolin** [comment]
DO NOT save the image as `.jpg`, save as `.png` instead. JPEG will compress images and modify the bits of pixels, which destroys the embedded LSB watermark. Because LSB is the simplest watermark, it is NOT robust to JPEG compression.

**Comment by 1685044068** [comment]
Thanks for your help, my problem is solved !
